/**
 * Mock data factories for demo mode
 * Provides comprehensive, realistic mock data for all entities
 */

import {
  DEMO_USER_ID,
  DEMO_WORKSPACE_ID,
  DEMO_WORKSPACE_MEMBER_ID,
  DEMO_CLIENT_ID_1,
  DEMO_CLIENT_ID_2,
  DEMO_CLIENT_ID_3,
  DEMO_CLIENT_ID_4,
  DEMO_CLIENT_ID_5,
  DEMO_CLIENT_ID_6,
  DEMO_CLIENT_ID_7,
  DEMO_CLIENT_ID_8,
  DEMO_CLIENT_ID_9,
  DEMO_CLIENT_ID_10,
  DEMO_PROJECT_ID_1,
  DEMO_PROJECT_ID_2,
  DEMO_PROJECT_ID_3,
  DEMO_PROJECT_ID_4,
  DEMO_PROJECT_ID_5,
  DEMO_PROJECT_ID_6,
  DEMO_PROJECT_ID_7,
  DEMO_PROJECT_ID_8,
  DEMO_PROJECT_ID_9,
  DEMO_PROJECT_ID_10,
  DEMO_PROJECT_ID_11,
  DEMO_PROJECT_ID_12,
  DEMO_PROJECT_ID_13,
  DEMO_PROJECT_ID_14,
  DEMO_PROJECT_ID_15,
  DEMO_PROJECT_ID_16,
  DEMO_PROJECT_ID_17,
  DEMO_PROJECT_ID_18,
  DEMO_PROJECT_ID_19,
  DEMO_PROJECT_ID_20,
  DEMO_PROJECT_ID_21,
  DEMO_PROJECT_ID_22,
  DEMO_PROJECT_ID_23,
  DEMO_PROJECT_ID_24,
  DEMO_PROJECT_ID_25,
  DEMO_VERSION_ID_1,
  DEMO_VERSION_ID_2,
  DEMO_VERSION_ID_3,
  DEMO_VERSION_ID_4,
  DEMO_VERSION_ID_5,
  DEMO_VERSION_ID_6,
  DEMO_VERSION_ID_7,
  DEMO_VERSION_ID_8,
  DEMO_VERSION_ID_9,
  DEMO_VERSION_ID_10,
  DEMO_VERSION_CO_1,
  DEMO_VERSION_CO_2,
  DEMO_EVENT_ID_1,
  DEMO_EVENT_ID_2,
  DEMO_EVENT_ID_3,
  DEMO_EVENT_ID_4,
  DEMO_EVENT_ID_5,
  DEMO_EVENT_ID_6,
  DEMO_EVENT_ID_7,
  DEMO_EVENT_ID_8,
  DEMO_PAYMENT_ID_1,
  DEMO_PAYMENT_ID_2,
  DEMO_PAYMENT_ID_3,
  DEMO_PAYMENT_ID_4,
  DEMO_PAYMENT_ID_5,
  DEMO_PAYMENT_ID_6,
  DEMO_PAYMENT_ID_7,
  DEMO_PAYMENT_ID_8,
  DEMO_PAYMENT_ID_9,
  DEMO_PAYMENT_ID_10,
  DEMO_FOLDER_ID_1,
  DEMO_FOLDER_ID_2,
  DEMO_FOLDER_ID_3,
  DEMO_STATUS_ID_ESTIMATE,
  DEMO_STATUS_ID_SOLD,
  DEMO_STATUS_ID_IN_PROGRESS,
  DEMO_STATUS_ID_COMPLETED,
  DEMO_APPOINTMENT_TYPE_ID_1,
  DEMO_APPOINTMENT_TYPE_ID_2,
  DEMO_APPOINTMENT_TYPE_ID_3,
  DEMO_MATERIAL_ID_1,
  DEMO_MATERIAL_ID_2,
  DEMO_MATERIAL_ID_3,
  DEMO_MATERIAL_ID_4,
  DEMO_MATERIAL_ID_5,
  DEMO_MATERIAL_ID_6,
  DEMO_MATERIAL_ID_7,
  DEMO_MATERIAL_ID_8,
  DEMO_MATERIAL_ID_9,
  DEMO_MATERIAL_ID_10,
  DEMO_MATERIAL_ID_11,
  DEMO_MATERIAL_ID_12,
  DEMO_MATERIAL_ID_13,
  DEMO_MATERIAL_ID_14,
  DEMO_MATERIAL_ID_15,
  DEMO_MATERIAL_ID_16,
  DEMO_MATERIAL_ID_17,
  DEMO_MATERIAL_ID_18,
  DEMO_MATERIAL_ID_19,
  DEMO_MATERIAL_ID_20,
  DEMO_LABOR_ID_1,
  DEMO_LABOR_ID_2,
  DEMO_LABOR_ID_3,
  DEMO_LABOR_ID_4,
  DEMO_LABOR_ID_5,
  DEMO_LABOR_ID_6,
  DEMO_LABOR_ID_7,
  DEMO_LABOR_ID_8,
  DEMO_LABOR_ID_9,
  DEMO_LABOR_ID_10,
  DEMO_LABOR_ID_11,
  DEMO_LABOR_ID_12,
  DEMO_PACKAGE_ID_1,
  DEMO_PACKAGE_ID_2,
  DEMO_PACKAGE_ID_3,
  DEMO_ASSIGNMENT_ID_1,
  DEMO_ASSIGNMENT_ID_2,
  DEMO_ASSIGNMENT_ID_3,
  DEMO_ASSIGNMENT_ID_4,
  DEMO_ASSIGNMENT_ID_5,
} from './constants';
import { Workspace, WorkspaceMember } from '@/contexts/WorkspaceContext';
import { Project, Client, EventItem } from '@/types';
import { User } from '@supabase/supabase-js';

const NOW = new Date().toISOString();
const ONE_MONTH_AGO = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
const TWO_MONTHS_AGO = new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString();

/**
 * Mock user (Supabase Auth User)
 */
export const getMockUser = (): User => ({
  id: DEMO_USER_ID,
  email: 'demo@masterviewportals.com',
  aud: 'authenticated',
  role: 'authenticated',
  email_confirmed_at: NOW,
  phone: null,
  confirmed_at: NOW,
  last_sign_in_at: NOW,
  app_metadata: {},
  user_metadata: {},
  identities: [],
  created_at: ONE_MONTH_AGO,
  updated_at: NOW,
});

/**
 * Mock workspace
 */
export const getMockWorkspace = (): Workspace => ({
  id: DEMO_WORKSPACE_ID,
  name: 'Demo Workspace',
  slug: 'demo-workspace',
  created_at: ONE_MONTH_AGO,
  updated_at: NOW,
  owner_id: DEMO_USER_ID,
});

/**
 * Mock workspace member
 */
export const getMockWorkspaceMember = (): WorkspaceMember => ({
  id: DEMO_WORKSPACE_MEMBER_ID,
  workspace_id: DEMO_WORKSPACE_ID,
  user_id: DEMO_USER_ID,
  created_at: ONE_MONTH_AGO,
  updated_at: NOW,
});

/**
 * Mock clients (10 total - clients 1-5 assigned to demo user, 6-10 not assigned)
 */
export const getMockClients = () => [
  {
    client_id: DEMO_CLIENT_ID_1,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'John & Sarah Johnson',
    email: 'john.johnson@email.com',
    phone: '(555) 123-4567',
    active_project: DEMO_PROJECT_ID_1,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    client_id: DEMO_CLIENT_ID_2,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Michael Chen',
    email: 'mchen@email.com',
    phone: '(555) 234-5678',
    active_project: DEMO_PROJECT_ID_2,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    client_id: DEMO_CLIENT_ID_3,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Emily Rodriguez',
    email: 'emily.r@email.com',
    phone: '(555) 345-6789',
    active_project: DEMO_PROJECT_ID_3,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    client_id: DEMO_CLIENT_ID_4,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Robert & Lisa Thompson',
    email: 'rthompson@email.com',
    phone: '(555) 456-7890',
    active_project: DEMO_PROJECT_ID_6,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    client_id: DEMO_CLIENT_ID_5,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'David Kim',
    email: 'dkim@email.com',
    phone: '(555) 567-8901',
    active_project: DEMO_PROJECT_ID_9,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    client_id: DEMO_CLIENT_ID_6,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Patricia Williams',
    email: 'pwilliams@email.com',
    phone: '(555) 678-9012',
    active_project: DEMO_PROJECT_ID_12,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    client_id: DEMO_CLIENT_ID_7,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'James & Maria Garcia',
    email: 'jgarcia@email.com',
    phone: '(555) 789-0123',
    active_project: DEMO_PROJECT_ID_15,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    client_id: DEMO_CLIENT_ID_8,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Jennifer Martinez',
    email: 'jmartinez@email.com',
    phone: '(555) 890-1234',
    active_project: DEMO_PROJECT_ID_18,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    client_id: DEMO_CLIENT_ID_9,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Christopher Brown',
    email: 'cbrown@email.com',
    phone: '(555) 901-2345',
    active_project: DEMO_PROJECT_ID_21,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    client_id: DEMO_CLIENT_ID_10,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Amanda & Thomas Wilson',
    email: 'awilson@email.com',
    phone: '(555) 012-3456',
    active_project: DEMO_PROJECT_ID_24,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
];

/**
 * Mock projects (database format) - 25+ projects, 2-3 per client
 */
export const getMockDbProjects = () => [
  // Client 1 (Johnson) - 3 projects
  {
    project_id: DEMO_PROJECT_ID_1,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_1,
    name: 'Kitchen Renovation',
    address: '123 Main Street, Anytown, ST 12345',
    project_type: 'Kitchen',
    status: 'Sold',
    active_version: DEMO_VERSION_ID_1,
    notes: 'Full kitchen remodel with custom cabinets and quartz countertops.',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_4,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_1,
    name: 'Deck Construction',
    address: '123 Main Street, Anytown, ST 12345',
    project_type: 'Outdoor',
    status: 'Estimate',
    active_version: null,
    notes: 'Composite deck with railing system.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_5,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_1,
    name: 'Basement Finishing',
    address: '123 Main Street, Anytown, ST 12345',
    project_type: 'Basement',
    status: 'Estimate',
    active_version: null,
    notes: 'Complete basement finishing with home theater area.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Client 2 (Chen) - 2 projects
  {
    project_id: DEMO_PROJECT_ID_2,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_2,
    name: 'Bathroom Remodel',
    address: '456 Oak Avenue, Anytown, ST 12345',
    project_type: 'Bathroom',
    status: 'Under Construction',
    active_version: DEMO_VERSION_ID_2,
    notes: 'Primary bathroom renovation with walk-in shower.',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_6,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_2,
    name: 'Guest Bathroom Update',
    address: '456 Oak Avenue, Anytown, ST 12345',
    project_type: 'Bathroom',
    status: 'Estimate',
    active_version: null,
    notes: 'Update guest bathroom with modern fixtures.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Client 3 (Rodriguez) - 3 projects
  {
    project_id: DEMO_PROJECT_ID_3,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_3,
    name: 'Master Suite Addition',
    address: '789 Pine Road, Anytown, ST 12345',
    project_type: 'Addition',
    status: 'Estimate',
    active_version: DEMO_VERSION_ID_3,
    notes: 'Adding master bedroom and bathroom suite.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_7,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_3,
    name: 'Home Office Renovation',
    address: '789 Pine Road, Anytown, ST 12345',
    project_type: 'Office',
    status: 'Sold',
    active_version: DEMO_VERSION_ID_4,
    notes: 'Convert spare room into professional home office.',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_8,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_3,
    name: 'Laundry Room Remodel',
    address: '789 Pine Road, Anytown, ST 12345',
    project_type: 'Laundry',
    status: 'Estimate',
    active_version: null,
    notes: 'Modernize laundry room with new cabinets and storage.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Client 4 (Thompson) - 2 projects
  {
    project_id: DEMO_PROJECT_ID_9,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_4,
    name: 'Whole House Renovation',
    address: '321 Elm Street, Anytown, ST 12345',
    project_type: 'Whole House',
    status: 'Under Construction',
    active_version: DEMO_VERSION_ID_5,
    notes: 'Complete home renovation including all major systems.',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_10,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_4,
    name: 'Outdoor Patio & Fireplace',
    address: '321 Elm Street, Anytown, ST 12345',
    project_type: 'Outdoor',
    status: 'Estimate',
    active_version: null,
    notes: 'Build covered patio with built-in fireplace.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Client 5 (Kim) - 3 projects
  {
    project_id: DEMO_PROJECT_ID_11,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_5,
    name: 'Kitchen & Dining Expansion',
    address: '654 Maple Drive, Anytown, ST 12345',
    project_type: 'Kitchen',
    status: 'Sold',
    active_version: DEMO_VERSION_ID_6,
    notes: 'Expand kitchen and create open concept dining area.',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_12,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_5,
    name: 'Master Bathroom Spa',
    address: '654 Maple Drive, Anytown, ST 12345',
    project_type: 'Bathroom',
    status: 'Estimate',
    active_version: null,
    notes: 'Create spa-like master bathroom with soaking tub.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_13,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_5,
    name: 'Garage Conversion',
    address: '654 Maple Drive, Anytown, ST 12345',
    project_type: 'Conversion',
    status: 'Estimate',
    active_version: null,
    notes: 'Convert garage into additional living space.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Client 6 (Williams) - NOT ASSIGNED - 2 projects
  {
    project_id: DEMO_PROJECT_ID_14,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_6,
    name: 'Kitchen Modernization',
    address: '987 Cedar Lane, Anytown, ST 12345',
    project_type: 'Kitchen',
    status: 'Estimate',
    active_version: null,
    notes: 'Update kitchen with modern appliances and finishes.',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_15,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_6,
    name: 'Bathroom Renovation',
    address: '987 Cedar Lane, Anytown, ST 12345',
    project_type: 'Bathroom',
    status: 'Estimate',
    active_version: null,
    notes: 'Complete bathroom renovation with new tile and fixtures.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Client 7 (Garcia) - NOT ASSIGNED - 3 projects
  {
    project_id: DEMO_PROJECT_ID_16,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_7,
    name: 'Second Story Addition',
    address: '147 Birch Court, Anytown, ST 12345',
    project_type: 'Addition',
    status: 'Estimate',
    active_version: null,
    notes: 'Add second story with two bedrooms and bathroom.',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_17,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_7,
    name: 'Kitchen Remodel',
    address: '147 Birch Court, Anytown, ST 12345',
    project_type: 'Kitchen',
    status: 'Estimate',
    active_version: null,
    notes: 'Full kitchen remodel with island and new appliances.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_18,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_7,
    name: 'Backyard Landscaping',
    address: '147 Birch Court, Anytown, ST 12345',
    project_type: 'Outdoor',
    status: 'Estimate',
    active_version: null,
    notes: 'Complete backyard landscaping with irrigation system.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Client 8 (Martinez) - NOT ASSIGNED - 2 projects
  {
    project_id: DEMO_PROJECT_ID_19,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_8,
    name: 'Master Suite Renovation',
    address: '258 Spruce Way, Anytown, ST 12345',
    project_type: 'Master Suite',
    status: 'Estimate',
    active_version: null,
    notes: 'Renovate master bedroom and bathroom suite.',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_20,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_8,
    name: 'Home Theater Room',
    address: '258 Spruce Way, Anytown, ST 12345',
    project_type: 'Entertainment',
    status: 'Estimate',
    active_version: null,
    notes: 'Convert basement into home theater with sound system.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Client 9 (Brown) - NOT ASSIGNED - 3 projects
  {
    project_id: DEMO_PROJECT_ID_21,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_9,
    name: 'Kitchen & Living Room Open Concept',
    address: '369 Willow Street, Anytown, ST 12345',
    project_type: 'Kitchen',
    status: 'Estimate',
    active_version: null,
    notes: 'Remove wall to create open concept kitchen and living room.',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_22,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_9,
    name: 'Guest Suite Addition',
    address: '369 Willow Street, Anytown, ST 12345',
    project_type: 'Addition',
    status: 'Estimate',
    active_version: null,
    notes: 'Add guest suite with bedroom and private bathroom.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_23,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_9,
    name: 'Outdoor Kitchen',
    address: '369 Willow Street, Anytown, ST 12345',
    project_type: 'Outdoor',
    status: 'Estimate',
    active_version: null,
    notes: 'Build outdoor kitchen with grill and bar area.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Client 10 (Wilson) - NOT ASSIGNED - 2 projects
  {
    project_id: DEMO_PROJECT_ID_24,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_10,
    name: 'Complete Home Renovation',
    address: '741 Ash Boulevard, Anytown, ST 12345',
    project_type: 'Whole House',
    status: 'Estimate',
    active_version: null,
    notes: 'Comprehensive home renovation including all rooms.',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    project_id: DEMO_PROJECT_ID_25,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_10,
    name: 'Pool & Deck Installation',
    address: '741 Ash Boulevard, Anytown, ST 12345',
    project_type: 'Outdoor',
    status: 'Estimate',
    active_version: null,
    notes: 'Install in-ground pool with surrounding deck area.',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
];

/**
 * Mock projects (mapped to Project type)
 */
export const getMockProjects = (): Project[] => {
  const clients = getMockClients();
  const dbProjects = getMockDbProjects();
  
  // Mock totals mapping for projects
  const projectTotals: Record<string, { totalCost: number; paid: number }> = {
    [DEMO_PROJECT_ID_1]: { totalCost: 85000, paid: 25000 },
    [DEMO_PROJECT_ID_2]: { totalCost: 45000, paid: 15000 },
    [DEMO_PROJECT_ID_3]: { totalCost: 125000, paid: 0 },
    [DEMO_PROJECT_ID_4]: { totalCost: 25000, paid: 0 },
    [DEMO_PROJECT_ID_5]: { totalCost: 35000, paid: 0 },
    [DEMO_PROJECT_ID_6]: { totalCost: 12000, paid: 0 },
    [DEMO_PROJECT_ID_7]: { totalCost: 28000, paid: 8000 },
    [DEMO_PROJECT_ID_8]: { totalCost: 15000, paid: 0 },
    [DEMO_PROJECT_ID_9]: { totalCost: 180000, paid: 50000 },
    [DEMO_PROJECT_ID_10]: { totalCost: 45000, paid: 0 },
    [DEMO_PROJECT_ID_11]: { totalCost: 95000, paid: 30000 },
    [DEMO_PROJECT_ID_12]: { totalCost: 55000, paid: 0 },
    [DEMO_PROJECT_ID_13]: { totalCost: 40000, paid: 0 },
    [DEMO_PROJECT_ID_14]: { totalCost: 65000, paid: 0 },
    [DEMO_PROJECT_ID_15]: { totalCost: 38000, paid: 0 },
    [DEMO_PROJECT_ID_16]: { totalCost: 150000, paid: 0 },
    [DEMO_PROJECT_ID_17]: { totalCost: 72000, paid: 0 },
    [DEMO_PROJECT_ID_18]: { totalCost: 32000, paid: 0 },
    [DEMO_PROJECT_ID_19]: { totalCost: 68000, paid: 0 },
    [DEMO_PROJECT_ID_20]: { totalCost: 42000, paid: 0 },
    [DEMO_PROJECT_ID_21]: { totalCost: 78000, paid: 0 },
    [DEMO_PROJECT_ID_22]: { totalCost: 88000, paid: 0 },
    [DEMO_PROJECT_ID_23]: { totalCost: 35000, paid: 0 },
    [DEMO_PROJECT_ID_24]: { totalCost: 200000, paid: 0 },
    [DEMO_PROJECT_ID_25]: { totalCost: 95000, paid: 0 },
  };
  
  return dbProjects.map((dbProject) => {
    const client = clients.find((c) => c.client_id === dbProject.client_id);
    const totals = projectTotals[dbProject.project_id] || { totalCost: 50000, paid: 0 };
    
    return {
      id: dbProject.project_id,
      clientId: dbProject.client_id || '',
      clientName: client?.name || 'Unknown Client',
      project: dbProject.name || 'Untitled Project',
      residence: dbProject.address || 'No address provided',
      crew: 'TBD',
      note: dbProject.notes || '',
      phaseIndex: 0,
      paid: totals.paid,
      totalCost: totals.totalCost,
      nextPayment: 0,
      dueStage: 'TBD',
      status: dbProject.status,
      assignedUserId: DEMO_USER_ID,
      quickNote: '',
    };
  });
};

/**
 * Mock project versions (drafts for projects with active versions)
 */
export const getMockProjectVersions = () => [
  {
    version_id: DEMO_VERSION_ID_1,
    project_id: DEMO_PROJECT_ID_1,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Contract',
    multiplier: 1.25,
    is_active: true,
    status: 'Contract',
    estimated_start_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    estimated_construction_time: 60,
    payment_1_percentage: 25,
    payment_2_percentage: 25,
    payment_3_percentage: 25,
    payment_4_percentage: 25,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
  },
  {
    version_id: DEMO_VERSION_CO_1,
    project_id: DEMO_PROJECT_ID_1,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Change Order 1',
    multiplier: 1,
    is_active: true,
    status: 'Change Order 1',
    estimated_start_date: null,
    estimated_construction_time: null,
    payment_1_percentage: null,
    payment_2_percentage: null,
    payment_3_percentage: null,
    payment_4_percentage: null,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
  },
  {
    version_id: DEMO_VERSION_CO_2,
    project_id: DEMO_PROJECT_ID_1,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Change Order 2',
    multiplier: 1,
    is_active: true,
    status: 'Change Order 2',
    estimated_start_date: null,
    estimated_construction_time: null,
    payment_1_percentage: null,
    payment_2_percentage: null,
    payment_3_percentage: null,
    payment_4_percentage: null,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
  },
  {
    version_id: DEMO_VERSION_ID_2,
    project_id: DEMO_PROJECT_ID_2,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Contract',
    multiplier: 1.20,
    is_active: true,
    status: 'Contract',
    estimated_start_date: new Date().toISOString().split('T')[0],
    estimated_construction_time: 45,
    payment_1_percentage: 30,
    payment_2_percentage: 30,
    payment_3_percentage: 20,
    payment_4_percentage: 20,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
  },
  {
    version_id: DEMO_VERSION_ID_3,
    project_id: DEMO_PROJECT_ID_3,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Initial Estimate',
    multiplier: 1.30,
    is_active: true,
    status: 'Estimate',
    estimated_start_date: null,
    estimated_construction_time: 90,
    payment_1_percentage: null,
    payment_2_percentage: null,
    payment_3_percentage: null,
    payment_4_percentage: null,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
  },
  {
    version_id: DEMO_VERSION_ID_4,
    project_id: DEMO_PROJECT_ID_7,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Contract',
    multiplier: 1.22,
    is_active: true,
    status: 'Contract',
    estimated_start_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    estimated_construction_time: 30,
    payment_1_percentage: 40,
    payment_2_percentage: 30,
    payment_3_percentage: 30,
    payment_4_percentage: 0,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
  },
  {
    version_id: DEMO_VERSION_ID_5,
    project_id: DEMO_PROJECT_ID_9,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Contract',
    multiplier: 1.28,
    is_active: true,
    status: 'Contract',
    estimated_start_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    estimated_construction_time: 120,
    payment_1_percentage: 25,
    payment_2_percentage: 25,
    payment_3_percentage: 25,
    payment_4_percentage: 25,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
  },
  {
    version_id: DEMO_VERSION_ID_6,
    project_id: DEMO_PROJECT_ID_11,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Contract',
    multiplier: 1.26,
    is_active: true,
    status: 'Contract',
    estimated_start_date: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    estimated_construction_time: 75,
    payment_1_percentage: 30,
    payment_2_percentage: 25,
    payment_3_percentage: 25,
    payment_4_percentage: 20,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
  },
  {
    version_id: DEMO_VERSION_ID_7,
    project_id: DEMO_PROJECT_ID_12,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Initial Estimate',
    multiplier: 1.35,
    is_active: true,
    status: 'Estimate',
    estimated_start_date: null,
    estimated_construction_time: 50,
    payment_1_percentage: null,
    payment_2_percentage: null,
    payment_3_percentage: null,
    payment_4_percentage: null,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
  },
  {
    version_id: DEMO_VERSION_ID_8,
    project_id: DEMO_PROJECT_ID_13,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Initial Estimate',
    multiplier: 1.32,
    is_active: true,
    status: 'Estimate',
    estimated_start_date: null,
    estimated_construction_time: 40,
    payment_1_percentage: null,
    payment_2_percentage: null,
    payment_3_percentage: null,
    payment_4_percentage: null,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
  },
  {
    version_id: DEMO_VERSION_ID_9,
    project_id: DEMO_PROJECT_ID_16,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Initial Estimate',
    multiplier: 1.40,
    is_active: true,
    status: 'Estimate',
    estimated_start_date: null,
    estimated_construction_time: 150,
    payment_1_percentage: null,
    payment_2_percentage: null,
    payment_3_percentage: null,
    payment_4_percentage: null,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
  },
  {
    version_id: DEMO_VERSION_ID_10,
    project_id: DEMO_PROJECT_ID_21,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Initial Estimate',
    multiplier: 1.28,
    is_active: true,
    status: 'Estimate',
    estimated_start_date: null,
    estimated_construction_time: 65,
    payment_1_percentage: null,
    payment_2_percentage: null,
    payment_3_percentage: null,
    payment_4_percentage: null,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
  },
];

/**
 * Mock project statuses
 */
export const getMockProjectStatuses = () => [
  {
    id: DEMO_STATUS_ID_ESTIMATE,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Estimate',
    color: '#8b5cf6',
    display_order: 0,
    is_required: false,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_STATUS_ID_SOLD,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Sold',
    color: '#10b981',
    display_order: 1,
    is_required: false,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_STATUS_ID_IN_PROGRESS,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Under Construction',
    color: '#3b82f6',
    display_order: 2,
    is_required: false,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_STATUS_ID_COMPLETED,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Completed',
    color: '#6b7280',
    display_order: 3,
    is_required: false,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
];

/**
 * Mock calendar events
 */
export const getMockCalendarEvents = (): EventItem[] => {
  const clients = getMockClients();
  const projects = getMockDbProjects();
  
  const today = new Date();
  const tomorrow = new Date(today.getTime() + 1 * 24 * 60 * 60 * 1000);
  const nextWeek = new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000);
  const twoWeeks = new Date(today.getTime() + 14 * 24 * 60 * 60 * 1000);
  const threeWeeks = new Date(today.getTime() + 21 * 24 * 60 * 60 * 1000);
  
  return [
    {
      id: DEMO_EVENT_ID_1,
      title: 'Initial consultation – Kitchen renovation',
      clientId: DEMO_CLIENT_ID_1,
      clientName: clients[0].name,
      projectId: projects[0].project_id,
      projectType: projects[0].project_type || 'Kitchen',
      appointmentTypeId: DEMO_APPOINTMENT_TYPE_ID_1,
      address: projects[0].address || '',
      assignedTo: [DEMO_USER_ID],
      date: nextWeek.toISOString().split('T')[0],
      time: '10:00',
    },
    {
      id: DEMO_EVENT_ID_2,
      title: 'Site visit – Bathroom remodel',
      clientId: DEMO_CLIENT_ID_2,
      clientName: clients[1].name,
      projectId: projects[1].project_id,
      projectType: projects[1].project_type || 'Bathroom',
      appointmentTypeId: DEMO_APPOINTMENT_TYPE_ID_2,
      address: projects[1].address || '',
      assignedTo: [DEMO_USER_ID],
      date: nextWeek.toISOString().split('T')[0],
      time: '14:00',
    },
    {
      id: DEMO_EVENT_ID_3,
      title: 'Follow-up – Master suite addition',
      clientId: DEMO_CLIENT_ID_3,
      clientName: clients[2].name,
      projectId: projects[2].project_id,
      projectType: projects[2].project_type || 'Addition',
      appointmentTypeId: DEMO_APPOINTMENT_TYPE_ID_3,
      address: projects[2].address || '',
      assignedTo: [DEMO_USER_ID],
      date: twoWeeks.toISOString().split('T')[0],
      time: '11:00',
    },
    {
      id: DEMO_EVENT_ID_4,
      title: 'Progress check – Whole house renovation',
      clientId: DEMO_CLIENT_ID_4,
      clientName: clients[3].name,
      projectId: projects[3].project_id,
      projectType: projects[3].project_type || 'Whole House',
      appointmentTypeId: DEMO_APPOINTMENT_TYPE_ID_1,
      address: projects[3].address || '',
      assignedTo: [DEMO_USER_ID],
      date: tomorrow.toISOString().split('T')[0],
      time: '09:00',
    },
    {
      id: DEMO_EVENT_ID_5,
      title: 'Design review – Kitchen',
      clientId: DEMO_CLIENT_ID_5,
      clientName: clients[4].name,
      projectId: projects[4].project_id,
      projectType: projects[4].project_type || 'Kitchen',
      appointmentTypeId: DEMO_APPOINTMENT_TYPE_ID_2,
      address: projects[4].address || '',
      assignedTo: [DEMO_USER_ID],
      date: nextWeek.toISOString().split('T')[0],
      time: '15:00',
    },
    {
      id: DEMO_EVENT_ID_6,
      title: 'Initial consultation – Kitchen modernization',
      clientId: DEMO_CLIENT_ID_6,
      clientName: clients[5].name,
      projectId: projects[5].project_id,
      projectType: projects[5].project_type || 'Kitchen',
      appointmentTypeId: DEMO_APPOINTMENT_TYPE_ID_1,
      address: projects[5].address || '',
      assignedTo: [],
      date: twoWeeks.toISOString().split('T')[0],
      time: '10:00',
    },
    {
      id: DEMO_EVENT_ID_7,
      title: 'Site visit – Second story addition',
      clientId: DEMO_CLIENT_ID_7,
      clientName: clients[6].name,
      projectId: projects[6].project_id,
      projectType: projects[6].project_type || 'Addition',
      appointmentTypeId: DEMO_APPOINTMENT_TYPE_ID_2,
      address: projects[6].address || '',
      assignedTo: [],
      date: threeWeeks.toISOString().split('T')[0],
      time: '13:00',
    },
    {
      id: DEMO_EVENT_ID_8,
      title: 'Kickoff – Master suite',
      clientId: DEMO_CLIENT_ID_8,
      clientName: clients[7].name,
      projectId: projects[7].project_id,
      projectType: projects[7].project_type || 'Master Suite',
      appointmentTypeId: DEMO_APPOINTMENT_TYPE_ID_1,
      address: projects[7].address || '',
      assignedTo: [],
      date: twoWeeks.toISOString().split('T')[0],
      time: '16:00',
    },
  ];
};

/**
 * Mock payments (incoming)
 */
export const getMockPayments = () => [
  {
    payment_id: DEMO_PAYMENT_ID_1,
    workspace_id: DEMO_WORKSPACE_ID,
    project_id: DEMO_PROJECT_ID_1,
    date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 15000,
    type: 'I',
    received_by: DEMO_USER_ID,
    for_field: 'Deposit',
    note: 'Initial deposit received',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    payment_id: DEMO_PAYMENT_ID_2,
    workspace_id: DEMO_WORKSPACE_ID,
    project_id: DEMO_PROJECT_ID_1,
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 10000,
    type: 'I',
    received_by: DEMO_USER_ID,
    for_field: 'Progress Payment',
    note: 'First progress payment',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    payment_id: DEMO_PAYMENT_ID_3,
    workspace_id: DEMO_WORKSPACE_ID,
    project_id: DEMO_PROJECT_ID_2,
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 15000,
    type: 'I',
    received_by: DEMO_USER_ID,
    for_field: 'Deposit',
    note: 'Project deposit',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    payment_id: DEMO_PAYMENT_ID_4,
    workspace_id: DEMO_WORKSPACE_ID,
    project_id: DEMO_PROJECT_ID_7,
    date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 8000,
    type: 'I',
    received_by: DEMO_USER_ID,
    for_field: 'Deposit',
    note: 'Home office project deposit',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    payment_id: DEMO_PAYMENT_ID_5,
    workspace_id: DEMO_WORKSPACE_ID,
    project_id: DEMO_PROJECT_ID_9,
    date: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 50000,
    type: 'I',
    received_by: DEMO_USER_ID,
    for_field: 'Deposit',
    note: 'Large project initial deposit',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    payment_id: DEMO_PAYMENT_ID_6,
    workspace_id: DEMO_WORKSPACE_ID,
    project_id: DEMO_PROJECT_ID_11,
    date: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 30000,
    type: 'I',
    received_by: DEMO_USER_ID,
    for_field: 'Deposit',
    note: 'Kitchen expansion deposit',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    payment_id: DEMO_PAYMENT_ID_7,
    workspace_id: DEMO_WORKSPACE_ID,
    project_id: DEMO_PROJECT_ID_1,
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 15000,
    type: 'I',
    received_by: DEMO_USER_ID,
    for_field: 'Progress Payment',
    note: 'Second progress payment',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    payment_id: DEMO_PAYMENT_ID_8,
    workspace_id: DEMO_WORKSPACE_ID,
    project_id: DEMO_PROJECT_ID_2,
    date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 12000,
    type: 'I',
    received_by: DEMO_USER_ID,
    for_field: 'Progress Payment',
    note: 'Bathroom remodel progress payment',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    payment_id: DEMO_PAYMENT_ID_9,
    workspace_id: DEMO_WORKSPACE_ID,
    project_id: DEMO_PROJECT_ID_9,
    date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 45000,
    type: 'I',
    received_by: DEMO_USER_ID,
    for_field: 'Progress Payment',
    note: 'Whole house renovation progress payment',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    payment_id: DEMO_PAYMENT_ID_10,
    workspace_id: DEMO_WORKSPACE_ID,
    project_id: DEMO_PROJECT_ID_11,
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    amount: 20000,
    type: 'I',
    received_by: DEMO_USER_ID,
    for_field: 'Progress Payment',
    note: 'Kitchen expansion progress payment',
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
];

/**
 * Mock appointment types
 */
export const getMockAppointmentTypes = () => [
  {
    id: DEMO_APPOINTMENT_TYPE_ID_1,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Consultation',
    color: '#3b82f6',
    duration_minutes: 60,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_APPOINTMENT_TYPE_ID_2,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Site Visit',
    color: '#10b981',
    duration_minutes: 90,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_APPOINTMENT_TYPE_ID_3,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Follow-up',
    color: '#f59e0b',
    duration_minutes: 30,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
];

/**
 * Mock attachment folders
 */
export const getMockAttachmentFolders = () => [
  {
    id: DEMO_FOLDER_ID_1,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Contracts',
    slug: 'contracts',
    display_order: 0,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_FOLDER_ID_2,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Photos',
    slug: 'photos',
    display_order: 1,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_FOLDER_ID_3,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Invoices',
    slug: 'invoices',
    display_order: 2,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
];

/**
 * Mock users table entry
 */
export const getMockUserRecord = () => ({
  id: DEMO_USER_ID,
  user_id: DEMO_USER_ID,
  name: 'Demo User',
  email: 'demo@masterviewportals.com',
  role: null,
  created_at: ONE_MONTH_AGO,
  updated_at: NOW,
});

/**
 * Mock client assignments (clients 1-5 assigned to demo user, 6-10 not assigned)
 */
export const getMockClientAssignments = () => [
  {
    id: DEMO_ASSIGNMENT_ID_1,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_1,
    workspace_member_id: DEMO_WORKSPACE_MEMBER_ID,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_ASSIGNMENT_ID_2,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_2,
    workspace_member_id: DEMO_WORKSPACE_MEMBER_ID,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_ASSIGNMENT_ID_3,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_3,
    workspace_member_id: DEMO_WORKSPACE_MEMBER_ID,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_ASSIGNMENT_ID_4,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_4,
    workspace_member_id: DEMO_WORKSPACE_MEMBER_ID,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_ASSIGNMENT_ID_5,
    workspace_id: DEMO_WORKSPACE_ID,
    client_id: DEMO_CLIENT_ID_5,
    workspace_member_id: DEMO_WORKSPACE_MEMBER_ID,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Clients 6-10 are NOT assigned (no assignments for them)
];

/**
 * Mock material options
 */
export const getMockMaterialOptions = () => [
  {
    id: DEMO_MATERIAL_ID_1,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Quartz Countertop',
    description: 'Premium quartz countertop material',
    price: 95.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_2,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Granite Countertop',
    description: 'Natural granite countertop',
    price: 85.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_3,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Ceramic Tile (12x24)',
    description: 'Large format ceramic tile',
    price: 8.50,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_4,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Porcelain Tile (12x12)',
    description: 'Standard porcelain floor tile',
    price: 6.75,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_5,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Hardwood Flooring (Oak)',
    description: 'Solid oak hardwood flooring',
    price: 12.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_6,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Custom Cabinets (per linear foot)',
    description: 'Custom built kitchen cabinets',
    price: 450.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_7,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Shower Tile (Mosaic)',
    description: 'Glass mosaic shower tile',
    price: 15.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_8,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Composite Decking',
    description: 'Low-maintenance composite decking',
    price: 18.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_9,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Paint (per gallon)',
    description: 'Premium interior paint',
    price: 45.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_10,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Backsplash Tile',
    description: 'Kitchen backsplash tile',
    price: 12.50,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_11,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Marble Countertop',
    description: 'Natural marble slab countertop',
    price: 125.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_12,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Vinyl Plank Flooring',
    description: 'Luxury vinyl plank, per sq ft',
    price: 5.50,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_13,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Subway Tile (3x6)',
    description: 'Classic white subway tile',
    price: 7.25,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_14,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Vanity Cabinet',
    description: 'Bathroom vanity base cabinet',
    price: 650.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_15,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Kitchen Sink (Stainless)',
    description: 'Undermount stainless steel sink',
    price: 380.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_16,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Faucet (Chrome)',
    description: 'Single-handle kitchen or bath faucet',
    price: 185.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_17,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Recessed Light Fixture',
    description: 'LED recessed can light',
    price: 42.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_18,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Drywall (4x8 sheet)',
    description: '1/2" standard drywall',
    price: 14.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_19,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Insulation (Batts)',
    description: 'R-15 fiberglass batt, per sq ft',
    price: 1.20,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_MATERIAL_ID_20,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Trim (Base/ Casing)',
    description: 'Paint-grade wood trim, linear ft',
    price: 3.75,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
];

/**
 * Mock labor options
 */
export const getMockLaborOptions = () => [
  {
    id: DEMO_LABOR_ID_1,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'General Contractor',
    description: 'General contractor services',
    price: 75.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_LABOR_ID_2,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Plumber',
    description: 'Licensed plumber hourly rate',
    price: 95.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_LABOR_ID_3,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Electrician',
    description: 'Licensed electrician hourly rate',
    price: 100.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_LABOR_ID_4,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Carpenter',
    description: 'Skilled carpenter hourly rate',
    price: 65.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_LABOR_ID_5,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Tile Installer',
    description: 'Professional tile installation',
    price: 55.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_LABOR_ID_6,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Painter',
    description: 'Professional painting services',
    price: 45.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_LABOR_ID_7,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'HVAC Technician',
    description: 'Heating and cooling installation/repair',
    price: 88.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_LABOR_ID_8,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Drywall Installer',
    description: 'Hang, tape, and finish drywall',
    price: 52.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_LABOR_ID_9,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Demolition Labor',
    description: 'Teardown and removal',
    price: 38.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_LABOR_ID_10,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Flooring Installer',
    description: 'Hardwood, laminate, vinyl installation',
    price: 58.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_LABOR_ID_11,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Cabinet Installer',
    description: 'Custom and stock cabinet installation',
    price: 72.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: DEMO_LABOR_ID_12,
    workspace_id: DEMO_WORKSPACE_ID,
    name: 'Design Consultation',
    description: 'Designer hourly rate',
    price: 95.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
];

/**
 * Mock packages (Admin > Pricing – package composer)
 */
export const getMockPackages = () => [
  {
    id: DEMO_PACKAGE_ID_1,
    name: 'Kitchen Essentials',
    packageGroupId: null,
    zeroLabor: false,
    workspaceId: DEMO_WORKSPACE_ID,
    createdBy: DEMO_USER_ID,
    createdAt: ONE_MONTH_AGO,
    updatedBy: DEMO_USER_ID,
    updatedAt: NOW,
    items: [],
  },
  {
    id: DEMO_PACKAGE_ID_2,
    name: 'Bathroom Remodel Standard',
    packageGroupId: null,
    zeroLabor: false,
    workspaceId: DEMO_WORKSPACE_ID,
    createdBy: DEMO_USER_ID,
    createdAt: ONE_MONTH_AGO,
    updatedBy: DEMO_USER_ID,
    updatedAt: NOW,
    items: [],
  },
  {
    id: DEMO_PACKAGE_ID_3,
    name: 'Tile & Flooring Package',
    packageGroupId: null,
    zeroLabor: false,
    workspaceId: DEMO_WORKSPACE_ID,
    createdBy: DEMO_USER_ID,
    createdAt: ONE_MONTH_AGO,
    updatedBy: DEMO_USER_ID,
    updatedAt: NOW,
    items: [],
  },
];

/**
 * Mock version materials (draft items for projects)
 */
export const getMockVersionMaterials = () => [
  // Version 1 (Kitchen Renovation)
  {
    id: 'vm-1-1',
    version_id: DEMO_VERSION_ID_1,
    material_id: DEMO_MATERIAL_ID_1,
    item_name: 'Quartz Countertop',
    quantity: 25,
    price: 95.00,
    waste_pct: 10,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vm-1-2',
    version_id: DEMO_VERSION_ID_1,
    material_id: DEMO_MATERIAL_ID_6,
    item_name: 'Custom Cabinets',
    quantity: 20,
    price: 450.00,
    waste_pct: 0,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vm-1-3',
    version_id: DEMO_VERSION_ID_1,
    material_id: DEMO_MATERIAL_ID_10,
    item_name: 'Backsplash Tile',
    quantity: 15,
    price: 12.50,
    waste_pct: 15,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Version 2 (Bathroom Remodel)
  {
    id: 'vm-2-1',
    version_id: DEMO_VERSION_ID_2,
    material_id: DEMO_MATERIAL_ID_3,
    item_name: 'Ceramic Tile',
    quantity: 30,
    price: 8.50,
    waste_pct: 10,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vm-2-2',
    version_id: DEMO_VERSION_ID_2,
    material_id: DEMO_MATERIAL_ID_7,
    item_name: 'Shower Tile',
    quantity: 20,
    price: 15.00,
    waste_pct: 15,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vm-1-4',
    version_id: DEMO_VERSION_ID_1,
    material_id: DEMO_MATERIAL_ID_9,
    item_name: 'Paint',
    quantity: 12,
    price: 45.00,
    waste_pct: 0,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vm-1-5',
    version_id: DEMO_VERSION_ID_1,
    material_id: DEMO_MATERIAL_ID_15,
    item_name: 'Kitchen Sink',
    quantity: 1,
    price: 380.00,
    waste_pct: 0,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vm-1-6',
    version_id: DEMO_VERSION_ID_1,
    material_id: DEMO_MATERIAL_ID_16,
    item_name: 'Faucet',
    quantity: 1,
    price: 185.00,
    waste_pct: 0,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vm-2-3',
    version_id: DEMO_VERSION_ID_2,
    material_id: DEMO_MATERIAL_ID_14,
    item_name: 'Vanity Cabinet',
    quantity: 1,
    price: 650.00,
    waste_pct: 0,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vm-2-4',
    version_id: DEMO_VERSION_ID_2,
    material_id: DEMO_MATERIAL_ID_16,
    item_name: 'Faucet',
    quantity: 2,
    price: 185.00,
    waste_pct: 0,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Version 3 (Addition – Initial Estimate)
  {
    id: 'vm-3-1',
    version_id: DEMO_VERSION_ID_3,
    material_id: DEMO_MATERIAL_ID_5,
    item_name: 'Hardwood Flooring',
    quantity: 120,
    price: 12.00,
    waste_pct: 10,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vm-3-2',
    version_id: DEMO_VERSION_ID_3,
    material_id: DEMO_MATERIAL_ID_18,
    item_name: 'Drywall',
    quantity: 45,
    price: 14.00,
    waste_pct: 10,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vm-3-3',
    version_id: DEMO_VERSION_ID_3,
    material_id: DEMO_MATERIAL_ID_9,
    item_name: 'Paint',
    quantity: 18,
    price: 45.00,
    waste_pct: 0,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Version 4 (Whole House)
  {
    id: 'vm-4-1',
    version_id: DEMO_VERSION_ID_4,
    material_id: DEMO_MATERIAL_ID_4,
    item_name: 'Porcelain Tile',
    quantity: 80,
    price: 6.75,
    waste_pct: 10,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vm-4-2',
    version_id: DEMO_VERSION_ID_4,
    material_id: DEMO_MATERIAL_ID_9,
    item_name: 'Paint',
    quantity: 35,
    price: 45.00,
    waste_pct: 0,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Version 5 (Master Suite)
  {
    id: 'vm-5-1',
    version_id: DEMO_VERSION_ID_5,
    material_id: DEMO_MATERIAL_ID_1,
    item_name: 'Quartz Countertop',
    quantity: 18,
    price: 95.00,
    waste_pct: 10,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vm-5-2',
    version_id: DEMO_VERSION_ID_5,
    material_id: DEMO_MATERIAL_ID_7,
    item_name: 'Shower Tile',
    quantity: 25,
    price: 15.00,
    waste_pct: 15,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Change Order 1 (deltas on sold contract = Version 1)
  {
    id: 'vco-1-1',
    version_id: DEMO_VERSION_CO_1,
    material_id: DEMO_MATERIAL_ID_1,
    item_name: 'Quartz Countertop',
    quantity: 3,
    price: 95.00,
    waste_pct: 10,
    baseline_version_material_id: 'vm-1-1',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vco-1-2',
    version_id: DEMO_VERSION_CO_1,
    material_id: DEMO_MATERIAL_ID_10,
    item_name: 'Backsplash Tile',
    quantity: 5,
    price: 12.50,
    waste_pct: 15,
    baseline_version_material_id: 'vm-1-3',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Change Order 2 (deltas + one new item)
  {
    id: 'vco-2-1',
    version_id: DEMO_VERSION_CO_2,
    material_id: DEMO_MATERIAL_ID_6,
    item_name: 'Custom Cabinets',
    quantity: -2,
    price: 450.00,
    waste_pct: 0,
    baseline_version_material_id: 'vm-1-2',
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vco-2-2',
    version_id: DEMO_VERSION_CO_2,
    material_id: DEMO_MATERIAL_ID_17,
    item_name: 'Recessed Light Fixture',
    quantity: 8,
    price: 42.00,
    waste_pct: 0,
    baseline_version_material_id: null,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
];

/**
 * Mock version labor (draft items for projects)
 */
export const getMockVersionLabor = () => [
  // Version 1 (Kitchen Renovation)
  {
    id: 'vl-1-1',
    version_id: DEMO_VERSION_ID_1,
    labor_id: DEMO_LABOR_ID_1,
    item_name: 'General Contractor',
    quantity: 80,
    price: 75.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-1-2',
    version_id: DEMO_VERSION_ID_1,
    labor_id: DEMO_LABOR_ID_2,
    item_name: 'Plumber',
    quantity: 16,
    price: 95.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-1-3',
    version_id: DEMO_VERSION_ID_1,
    labor_id: DEMO_LABOR_ID_3,
    item_name: 'Electrician',
    quantity: 20,
    price: 100.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Version 2 (Bathroom Remodel)
  {
    id: 'vl-2-1',
    version_id: DEMO_VERSION_ID_2,
    labor_id: DEMO_LABOR_ID_1,
    item_name: 'General Contractor',
    quantity: 40,
    price: 75.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-2-2',
    version_id: DEMO_VERSION_ID_2,
    labor_id: DEMO_LABOR_ID_2,
    item_name: 'Plumber',
    quantity: 12,
    price: 95.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-2-3',
    version_id: DEMO_VERSION_ID_2,
    labor_id: DEMO_LABOR_ID_5,
    item_name: 'Tile Installer',
    quantity: 24,
    price: 55.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-1-4',
    version_id: DEMO_VERSION_ID_1,
    labor_id: DEMO_LABOR_ID_6,
    item_name: 'Painter',
    quantity: 24,
    price: 45.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-1-5',
    version_id: DEMO_VERSION_ID_1,
    labor_id: DEMO_LABOR_ID_11,
    item_name: 'Cabinet Installer',
    quantity: 32,
    price: 72.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-2-4',
    version_id: DEMO_VERSION_ID_2,
    labor_id: DEMO_LABOR_ID_6,
    item_name: 'Painter',
    quantity: 16,
    price: 45.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Version 3 labor
  {
    id: 'vl-3-1',
    version_id: DEMO_VERSION_ID_3,
    labor_id: DEMO_LABOR_ID_1,
    item_name: 'General Contractor',
    quantity: 120,
    price: 75.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-3-2',
    version_id: DEMO_VERSION_ID_3,
    labor_id: DEMO_LABOR_ID_8,
    item_name: 'Drywall Installer',
    quantity: 60,
    price: 52.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-3-3',
    version_id: DEMO_VERSION_ID_3,
    labor_id: DEMO_LABOR_ID_10,
    item_name: 'Flooring Installer',
    quantity: 40,
    price: 58.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-3-4',
    version_id: DEMO_VERSION_ID_3,
    labor_id: DEMO_LABOR_ID_6,
    item_name: 'Painter',
    quantity: 48,
    price: 45.00,
    created_at: ONE_MONTH_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Version 4 labor
  {
    id: 'vl-4-1',
    version_id: DEMO_VERSION_ID_4,
    labor_id: DEMO_LABOR_ID_1,
    item_name: 'General Contractor',
    quantity: 60,
    price: 75.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-4-2',
    version_id: DEMO_VERSION_ID_4,
    labor_id: DEMO_LABOR_ID_5,
    item_name: 'Tile Installer',
    quantity: 35,
    price: 55.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-4-3',
    version_id: DEMO_VERSION_ID_4,
    labor_id: DEMO_LABOR_ID_6,
    item_name: 'Painter',
    quantity: 40,
    price: 45.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  // Version 5 labor
  {
    id: 'vl-5-1',
    version_id: DEMO_VERSION_ID_5,
    labor_id: DEMO_LABOR_ID_1,
    item_name: 'General Contractor',
    quantity: 100,
    price: 75.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-5-2',
    version_id: DEMO_VERSION_ID_5,
    labor_id: DEMO_LABOR_ID_2,
    item_name: 'Plumber',
    quantity: 24,
    price: 95.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
  {
    id: 'vl-5-3',
    version_id: DEMO_VERSION_ID_5,
    labor_id: DEMO_LABOR_ID_5,
    item_name: 'Tile Installer',
    quantity: 45,
    price: 55.00,
    created_at: TWO_MONTHS_AGO,
    updated_at: NOW,
    created_by: DEMO_USER_ID,
    updated_by: DEMO_USER_ID,
  },
];

